--- #YAML:1.0
name: DateTime-Event-SolarTerm
version: 0.01
license: perl
distribution_type: module
requires:
  DateTime: 0
  DateTime::Set: 0
  DateTime::Util::Astro::Sun: 0
  DateTime::Util::Calc: 0
  Params::Validate: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  DateTime::Event::SolarTerm:
    file: lib/DateTime/Event/SolarTerm.pm
    version: 0.01
generated_by: Module::Build version 0.21
