--- #YAML:1.0
name: DateTime-Event-SolarTerm
version: 0.03
author:
  - Daisuke Maki E<lt>daisuke@cpan.orgE<gt>
abstract: DateTime Extension to Calculate Solar Terms
license: perl
requires:
  DateTime: 0
  DateTime::Set: 0
  DateTime::Util::Astro::Sun: 0
  DateTime::Util::Calc: 0
  Params::Validate: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  DateTime::Event::SolarTerm:
    file: lib/DateTime/Event/SolarTerm.pm
    version: 0.03
generated_by: Module::Build version 0.22
