--- 
abstract: DateTime Extension to Calculate Solar Terms
author: Copyright (c) 2003-2007 Daisuke Maki <daisuke@endeworks.jp>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DateTime-Event-SolarTerm
no_index: 
  directory: 
    - inc
    - t
requires: 
  DateTime: 0
  DateTime::Set: 0
  DateTime::Util::Astro::Sun: 0.11
  DateTime::Util::Calc: 0.12
  Params::Validate: 0
version: 0.05
